"""
Utility functions for the Recommendation Agent.
"""

import os
from langchain_groq import ChatGroq


def load_groq_model():
    """
    Load and return the Groq LLM.

    Returns
    -------
    ChatGroq
        Initialized Groq model.
    """

    return ChatGroq(
        api_key=os.getenv("GROQ_API_KEY"),
        model_name="llama-3.3-70b-versatile",
        temperature=0.2
    )


def invoke_llm(
    groq_model,
    prompt: str
) -> str:
    """
    Invoke the Groq model with the given prompt.

    Parameters
    ----------
    groq_model : ChatGroq
        Initialized Groq model.

    prompt : str
        Prompt sent to the model.

    Returns
    -------
    str
        Raw response generated by the model.
    """

    response = groq_model.invoke(prompt)

    return response.content